# example_capsule.yaml
name: example_capsule
vehicle:
  mass: 1500.0
  Aref: 1.8
  Rn: 0.5
  Cl: 0.0
entry:
  v0: 7800.0
  gamma_deg: -5.0
  h0: 120000.0
control:
  auto_bank: true
  q_target: 4.0e6
  max_bank: 60
  bank_rate: 15
physics:
  heat_model: sutton
  Re_lam: 1e6
  Re_crit: 5e6
output:
  out_csv: ../../data/capsule_run.csv
